version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: fullstack_backend
    volumes:
      - .:/app
    env_file:
      - .env
    command: uv run python backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: node:20
    working_dir: /app
    container_name: fullstack_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

  celery:
    build:
      context: backend/.
      dockerfile: ./Dockerfile
    container_name: fullstack_celery
    volumes:
      - .:/app
    env_file:
      - .env
    command: uv run celery -A backend.config worker -l info
    depends_on:
      - backend
      - redis

  postgres:
    image: postgres:17
    container_name: fullstack_postgres
    environment:
      POSTGRES_DB: template_db
      POSTGRES_USER: template_user
      POSTGRES_PASSWORD: template_pw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fullstack_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
